print ("A SIMPLE CALCULATOR")
print ("choose the operation to be performed")
print ("1. Add\n 2.Subtract \n 3.Multiplication \n 4.Division")
choice=input("Enter the Choice")
choice=choice.lower()
if choice=="1" or choice=="add":
    a=input("Enter the number ")
    a=int(a)
    b=input("Enter Second Number ")
    b=int(b)
    print (a+b)
    exit()
elif choice=="2" or choice=="subtract":
    a=input("Enter First number ")
    a=int(a)
    b=input("Enter Second Number ")
    b=int(b)
    print (a-b)
    exit()
elif choice=="3" or choice=="multiplication":
    a=input("Enter First number ")
    a=int(a)
    b=input("Enter Second Number ")
    b=int(b)
    print (a*b)
    exit()
elif choice=="4" or choice=="division":
    a=input("Enter First number ")
    a=int(a)
    b=input("Enter Second Number ")
    b=int(b)
    print (a*b)
    exit()
else:
    print   ("Invalid Operator")